### ISSUE TITLE
Updating this guide for VSHM.

### ISSUE THREAD

**Issue by Xtortion** [teralove/vsnm-lakan-guide#1]
With VSHM coming next week to EU already, is there any chance you will be updating this guide for the hard mode as well?

Will be much appreciated! 

Thanks in advance already.

**Comment by teralove** [comment]
Yeah my plan was to make a HM version too.
But I only have NA Tera installed, so we'll have to wait for NA patch first.
I'll definitely make a HM version if nobody else makes one before then.

**Comment by Xtortion** [comment]
I'm happy to hear that!

Thanks for all your work you put into this :)

**Comment by domenato** [comment]
teralove, can you make a sample guide how to capture boss mechanics?

**Comment by teralove** [comment]
@domenato, sure I'll make one within a week.

**Comment by teralove** [comment]
@Xtortion [https://github.com/teralove/vshm-lakan-guide](https://github.com/teralove/vshm-lakan-guide)
@domenato [https://pastebin.com/aiw538W2](https://pastebin.com/aiw538W2)
